export const supermarketItemsArray = [
    "apple",
    "banana",
    "orange",
    "grape",
    "pear",
    "peach",
    "plum",
    "kiwi",
    "mango",
    "pineapple",
    "watermelon",
    "cantaloupe",
    "honeydew",
    "strawberry",
    "blueberry",
    "raspberry",
    "blackberry",
    "cherry",
    "apricot",
    "avocado",
    "lemon",
    "lime",
    "grapefruit",
    "pomegranate",
    "fig",
    "date",
    "coconut",
    "durian",
    "passion fruit",
    "dragon fruit",
    "papaya",
    "lychee",
    "starfruit",
    "persimmon",
    "rambutan",
    "jackfruit",
    "plantain",
    "breadfruit",
    "cranberry",
    "gooseberry",
    "mulberry",
    "loganberry",
    "boysenberry",
    "olive",
    "tomato",
    "cucumber",
    "lettuce",
    "spinach",
    "kale",
    "arugula",
    "broccoli",
    "cauliflower",
    "cabbage",
    "brussels sprouts",
    "asparagus",
    "celery",
    "carrot",
    "beet",
    "radish",
    "turnip",
    "parsnip",
    "rutabaga",
    "potato",
    "sweet potato",
    "yam",
    "onion",
    "garlic",
    "leek",
    "shallot",
    "chive",
    "scallion",
    "ginger",
    "turmeric",
    "pepper",
    "bell pepper",
    "chili pepper",
    "jalapeno",
    "habanero",
    "poblano",
    "serrano",
    "corn",
    "zucchini",
    "squash",
    "pumpkin",
    "eggplant",
    "okra",
    "green bean",
    "pea",
    "lentil",
    "chickpea",
    "soybean",
    "edamame",
    "mushroom",
    "truffle",
    "artichoke",
    "fennel",
    "bok choy",
    "collard greens",
    "mustard greens",
    "swiss chard",
    "rhubarb",
    "dandelion greens",
    "seaweed",
    "algae",
    "kohlrabi",
    "jicama",
    "radicchio",
    "endive",
    "watercress",
    "bean sprout",
    "alfalfa sprout",
    "brussel sprout",
    "cress",
    "herbs",
    "parsley",
    "cilantro",
    "basil",
    "oregano",
    "thyme",
    "rosemary",
    "sage",
    "mint",
    "dill",
    "tarragon",
    "marjoram",
    "lavender",
    "bay leaf",
    "chocolate",
    "candy",
    "sugar",
    "honey",
    "jam",
    "jelly",
    "peanut butter",
    "almond butter",
    "hazelnut spread",
    "bread",
    "bagel",
    "croissant",
    "muffin",
    "donut",
    "pastry",
    "cake",
    "pie",
    "biscuit",
    "cracker",
    "cookie",
    "cereal",
    "granola",
    "oatmeal",
    "pasta",
    "spaghetti",
    "macaroni",
    "noodle",
    "rice",
    "quinoa",
    "barley",
    "wheat",
    "cornmeal",
    "flour",
    "cornstarch",
    "baking powder",
    "baking soda",
    "yeast",
    "egg",
    "milk",
    "cream",
    "butter",
    "cheese",
    "yogurt",
    "ice cream",
    "sour cream",
    "cottage cheese",
    "cream cheese",
    "feta cheese",
    "goat cheese",
    "parmesan cheese",
    "cheddar cheese",
    "swiss cheese",
    "mozzarella cheese",
    "blue cheese",
    "brie cheese",
    "camembert cheese",
    "ricotta cheese",
    "provolone cheese",
    "gouda cheese",
    "chicken",
    "turkey",
    "duck",
    "goose",
    "beef",
    "pork",
    "lamb",
    "veal",
    "bacon",
    "sausage",
    "ham",
    "salami",
    "pepperoni",
    "prosciutto",
    "meatball",
    "steak",
    "ribeye",
    "tenderloin",
    "sirloin",
    "brisket",
    "roast",
    "ground beef",
    "ground turkey",
    "ground pork",
    "ground chicken",
    "fish",
    "salmon",
    "tuna",
    "cod",
    "haddock",
    "trout",
    "halibut",
    "flounder",
    "mackerel",
    "sardine",
    "anchovy",
    "shrimp",
    "prawn",
    "crab",
    "lobster",
    "clams",
    "oyster",
    "mussel",
    "scallop",
    "squid",
    "octopus",
    "snail",
    "tofu",
    "tempeh",
    "seitan",
    "bean curd",
    "almond milk",
    "soy milk",
    "oat milk",
    "rice milk",
    "coconut milk",
    "juice",
    "orange juice",
    "apple juice",
    "grape juice",
    "cranberry juice",
    "tomato juice",
    "carrot juice",
    "lemonade",
    "iced tea",
    "coffee",
    "tea",
    "water",
    "sparkling water",
    "soda",
    "cola",
    "lemon-lime soda",
    "root beer",
    "ginger ale",
    "sports drink",
    "energy drink",
    "beer",
    "wine",
    "red wine",
    "white wine",
    "rose wine",
    "champagne",
    "whiskey",
    "vodka",
    "rum",
    "gin",
    "tequila",
    "brandy",
    "liqueur",
    "spices",
    "salt",
    "pepper",
    "cinnamon",
    "nutmeg",
    "clove",
    "cardamom",
    "cumin",
    "coriander",
    "paprika",
    "chili powder",
    "cayenne pepper",
    "turmeric",
    "saffron",
    "vanilla",
    "ginger",
    "garlic powder",
    "onion powder",
    "mustard",
    "mayonnaise",
    "ketchup",
    "soy sauce",
    "vinegar",
    "olive oil",
    "vegetable oil",
    "canola oil",
    "coconut oil",
    "peanut oil",
    "sesame oil",
    "sunflower oil",
    "avocado oil",
    "grape seed oil",
    "corn oil",
    "bread crumbs",
    "crouton",
    "pasta sauce",
    "tomato sauce",
    "marinara sauce",
    "alfredo sauce",
    "pesto",
    "barbecue sauce",
    "hot sauce",
    "salsa",
    "hummus",
    "guacamole",
    "sour cream",
    "yogurt",
    "cottage cheese",
    "parmesan",
    "cheddar",
    "mozzarella",
    "provolone",
    "swiss",
    "blue cheese",
    "feta",
    "goat cheese",
    "brie",
    "camembert",
    "ricotta",
    "cream cheese",
    "butter",
    "margarine",
    "whipped cream",
    "sour cream",
    "milk",
    "cream",
    "half-and-half",
    "egg",
    "egg white",
    "egg yolk",
    "tofu",
    "tempeh",
    "seitan",
    "almond",
    "peanut",
    "cashew",
    "pistachio",
    "walnut",
    "pecan",
    "hazelnut",
    "macadamia",
    "brazil nut",
    "pine nut",
    "sunflower seed",
    "pumpkin seed",
    "chia seed",
    "flaxseed"
];

export const supermarketItemsSet = new Set(supermarketItemsArray);

export const isSupermarketItem = (item: string): boolean => {
    return supermarketItemsSet.has(item);
};
